#!/bin/bash -eu

test -n "$1" || (echo "parameter <container> is missing" && exit 1)

root="$(cd `dirname $0`/../.. && pwd)"
container=$1

version_tag="dzwicker/${container}:$(cat "${root}/scripts/.build/version")"
latest_tag="dzwicker/${container}:latest"

(cd "${root}/etc/${container}"
    docker build --tag="${version_tag}" .
)

docker tag -f "${version_tag}" "${latest_tag}"
