#!/bin/bash -e

args="$*"

port="8080"
while getopts :p:u: flag; do
    case ${flag} in
        u)
            path="$OPTARG"
            ;;
        p)
            port="$OPTARG"
            ;;
        *)
            ;;
    esac
done
shift $(( OPTIND - 1 ));

url="http://$(boot2docker ip):${port}"
if [ "x${path}" != "x" ]; then
    url="${url}/${path}"
fi
echo "${url}"
open "${url}"
