#!/bin/bash -e

test -n "$1" || (echo "parameter <container> is missing" && exit 1)

root="$(cd `dirname $0`/../.. && pwd)"

args="$*"

detach=false
name=false
while getopts :dnv:e:c: flag; do
    case ${flag} in
        c)
            container="$OPTARG"
            ;;
        d)
            detach=true
            ;;
        n)
            name=true
            ;;
        v)
            volume="$OPTARG"
            ;;
        e)
            environment="$OPTARG"
            ;;
        *)
            ;;
    esac
done
shift $(( OPTIND - 1 ));

version_tag="dzwicker/${container}:$(cat "${root}/scripts/.build/version")"

command="docker run --net=host"

if ${detach}; then
    command="${command} -d"
else
    command="${command} -ti"
fi
if [ -n "${environment}" ]; then
    command="${command} -e ${environment}"
fi
if [ -n "${volume}" ]; then
    command="${command} -v ${volume}"
fi
if ${name}; then
    command="${command} --name=${container}"
fi

command="${command} ${version_tag}"

echo "${command}"
if ${detach}; then
    id=$(${command})
    echo ${id} > "${root}/${container}.id"
else
    ${command}
fi
