#!/bin/bash -eu

test -n "$1" || (echo "parameter <container> is missing" && exit 1)

root="$(cd `dirname $0`/../.. && pwd)"

args="$*"

detach=false
while getopts :dc: flag; do
    case ${flag} in
        c)
            container="$OPTARG"
            ;;
        d)
            detach=true
            ;;
        *)
            ;;
    esac
done
shift $(( OPTIND - 1 ));

version_tag="dzwicker/${container}:$(cat "${root}/script/.build/version")"

if ${detach}; then
    id=$(docker run -d --net=host ${version_tag})
    echo ${id} > "${root}/${container}.id"
else
    docker run -ti --net=host ${version_tag}
fi
