#!/bin/bash -eu

test -n "$1" || (echo "parameter <container> is missing" && exit 1)

root="$(cd `dirname $0`/../.. && pwd)"
container=$1

version_tag="dzwicker/${container}:$(cat "${root}/script/.build/version")"

docker run -ti --net="host" "${version_tag}"
